version: '3'
services:
  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: yourpassword
      MYSQL_DATABASE: prova
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - app-network

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 80:80
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/app
    ports:
      - 3333:3333
    depends_on:
      - mysql
    networks:
      - app-network

volumes:
  mysql_data:


networks:
  app-network:
    driver: bridge
