version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_DB_HOST=mysql
      - MYSQL_DB_USER=root
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=yourdbname
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
